name: NoVoidDamage
main: me.asofold.bpl.novoiddamage.NoVoidDamage
version: 0.3.0
# database: false
# load: startup
author: asofold


commands:
  novoiddamage:
    description: "Manage the plugin No Void Damage (reload)."
    usage: "novoiddamage ... for: reload"
